#index:
#    path: /
#    controller: App\Controller\DefaultController::index
customer_list:
  path: /api/customers
  controller: App\Controller\CustomerController:indexAction
  methods: [GET]

customer_create:
  path: /api/customers
  controller: App\Controller\CustomerController:createAction
  methods: [POST]

similar_customer_route:
  path: /api/customer/route/comparable/{id}
  controller: App\Controller\CustomerController:findComparableCustomerJournies
  methods: [GET]
  requirements:
    id: '\d+'

customer_route:
  path: /api/customer/route/{id}
  controller: App\Controller\AccessLogController:findCustomerJourney
  methods: [GET]
  requirements:
    id: '\d+'

url_create:
  path: /api/urls
  controller: App\Controller\UrlController:createAction
  methods: [POST]

url_list:
  path: /api/urls
  controller: App\Controller\UrlController:indexAction
  methods: [GET]

access_log_create:
  path: /api/accesslog
  controller: App\Controller\AccessLogController:createAction
  methods: [POST]

access_log_list:
  path: /api/accesslog
  controller: App\Controller\AccessLogController:indexAction
  methods: [GET]

access_log_show:
  path: /api/accesslog/id
  controller: App\Controller\AccessLogController:getIndividualLinkAction
  methods: [POST]

access_log_show_by_type:
  path: /api/accesslog/type
  controller: App\Controller\AccessLogController:getUrlByType
  methods: [POST]


